project_id = "ojtriykgfquhgywqipxg"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-update-email]
verify_jwt = true

[functions.admin-update-password]
verify_jwt = true

[functions.chat-agent]
verify_jwt = true

[functions.demo-chat]
verify_jwt = false
