project_id = "ojtriykgfquhgywqipxg"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-update-email]
verify_jwt = true

[functions.admin-update-password]
verify_jwt = true

[functions.chat-agent]
verify_jwt = true

[functions.demo-chat]
verify_jwt = false

[functions.create-checkout-stripe]
verify_jwt = true

[functions.create-checkout-asaas]
verify_jwt = true

[functions.webhook-stripe]
verify_jwt = false

[functions.webhook-asaas]
verify_jwt = false

[functions.test-webhook-asaas]
verify_jwt = false
